<?php

namespace App\Http\Controllers\API;

use App\Mail\LeadSignupNotification;
use App\Models\Admin;
use App\Models\ClientContact;
use App\Models\ClientEmail;
use App\Models\Staff;
use App\Services\ClientReferenceService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class SignupController extends BaseController
{
    /**
     * Signup API: create a new lead (type=lead) in admins, client_contacts, and client_emails.
     * - client_id is autogenerated and unique.
     * - Phone and email must be unique; otherwise validation errors returned.
     * - Phone type and Email type are not accepted; both default to "Personal".
     */
    public function signup(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'dob' => 'nullable|string|max:50',
            'gender' => 'required|string|max:255',
            'marital_status' => 'nullable|string|max:255',
            'phone' => 'required|string|max:50',
            'country_code' => 'nullable|string|max:20',
            'email' => 'required|email|max:255',
            'password' => 'required|string|min:8|max:255',
        ], [
            'password.min' => 'The password must be at least 8 characters.',
        ]);

        if ($validator->fails()) {
            return $this->sendError('Validation failed.', $validator->errors()->toArray(), 422);
        }

        $data = $validator->validated();
        $email = strtolower(trim($data['email']));
        $phoneNormalized = $this->normalizePhoneForSignup(
            $data['phone'],
            $data['country_code'] ?? null
        );

        // Unique phone: check admins and client_contacts
        if (Admin::where('phone', $phoneNormalized)->exists()) {
            return $this->sendError('phone number is already exist', ['phone' => ['phone number is already exist']], 422);
        }
        if (ClientContact::where('phone', $phoneNormalized)->exists()) {
            return $this->sendError('phone number is already exist', ['phone' => ['phone number is already exist']], 422);
        }

        // Unique email: check admins and client_emails
        if (Admin::whereRaw('LOWER(email) = ?', [$email])->exists()) {
            return $this->sendError('Email is already exist', ['email' => ['Email is already exist']], 422);
        }
        if (ClientEmail::whereRaw('LOWER(email) = ?', [$email])->exists()) {
            return $this->sendError('Email is already exist', ['email' => ['Email is already exist']], 422);
        }

        $countryCode = $this->extractCountryCodeForSignup($data['phone'], $data['country_code'] ?? null);

        // Parse DOB (dd/mm/yyyy or similar) and calculate age from it
        $dob = null;
        $age = null;
        if (!empty($data['dob'])) {
            $parts = preg_split('/[\/\-]/', trim($data['dob']), 3);
            if (count($parts) === 3) {
                $dob = sprintf('%04d-%02d-%02d', (int) $parts[2], (int) $parts[1], (int) $parts[0]);
                try {
                    $dobDate = Carbon::parse($dob);
                    if (!$dobDate->isFuture()) {
                        $age = $dobDate->diff(Carbon::now())->format('%y years %m months');
                    }
                } catch (\Exception $e) {
                    // Keep age null if parse fails
                }
            }
        }

        DB::beginTransaction();
        try {
            $referenceService = app(ClientReferenceService::class);
            $reference = $referenceService->generateClientReference($data['first_name']);
            $clientId = $reference['client_id'];
            $clientCounter = $reference['client_counter'];

            $systemUserId = (int) config('app.system_user_id', 1);

            $adminData = [
                'user_id' => $systemUserId,
                'password' => Hash::make($data['password']),
                'client_counter' => $clientCounter,
                'client_id' => $clientId,
                'status' => '1',
                'type' => 'lead',
                'is_archived' => 0,
                'is_deleted' => null,
                'verified' => 0,
                'cp_status' => 1,
                'cp_code_verify' => 0,
                'australian_study' => 0,
                'specialist_education' => 0,
                'regional_study' => 0,
                'is_company' => 0,
                'first_name' => $data['first_name'],
                'last_name' => $data['last_name'],
                'gender' => $data['gender'],
                'dob' => $dob,
                'age' => $age,
                'marital_status' => $data['marital_status'] ?? null,
                'contact_type' => 'Personal',
                'country_code' => $countryCode,
                'phone' => $phoneNormalized,
                'email_type' => 'Personal',
                'email' => $email,
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $adminId = DB::table('admins')->insertGetId($adminData);

            ClientContact::create([
                'admin_id' => $systemUserId,
                'client_id' => $adminId,
                'contact_type' => 'Personal',
                'phone' => $phoneNormalized,
                'country_code' => $countryCode,
                'is_verified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            ClientEmail::create([
                'admin_id' => $systemUserId,
                'client_id' => $adminId,
                'email_type' => 'Personal',
                'email' => $email,
                'is_verified' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::commit();

            Log::info('Signup API: lead created', [
                'admin_id' => $adminId,
                'client_id' => $clientId,
                'email' => $email,
            ]);

            // Notify super admin(s) (role=1 in staff table)
            $this->sendLeadSignupNotificationToSuperAdmins($clientId, $data['first_name'], $data['last_name'], $email, $phoneNormalized);

            return response()->json([
                'success' => true,
                'message' => 'Signup successful. You can login in app but some features will be disabled until admin approve your account.',
                'data' => [
                    'id' => $adminId,
                    'client_id' => $clientId,
                    'first_name' => $data['first_name'],
                    'last_name' => $data['last_name'],
                    'email' => $email,
                    'phone' => $phoneNormalized,
                ],
            ], 201);
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Signup API error: ' . $e->getMessage(), [
                'trace' => $e->getTraceAsString(),
                'request' => $request->only(['first_name', 'last_name', 'email']),
            ]);
            return $this->sendError('An error occurred while creating your account. Please try again.', [], 500);
        }
    }

    /**
     * Send email to all super admins (role=1 in staff table) when a lead signs up from the Client mobile app.
     * Subject: Lead - {client_id} is generated from Client mobile app
     * Body: Lead details and instruction to convert to Client, create matter, assign client portal access.
     */
    private function sendLeadSignupNotificationToSuperAdmins(string $clientId, string $firstName, string $lastName, string $leadEmail, string $leadPhone): void
    {
        $superAdmins = Staff::where('role', 1)
            ->where('status', 1)
            ->whereNotNull('email')
            ->where('email', '!=', '')
            ->get();

        $mailable = new LeadSignupNotification($clientId, $firstName, $lastName, $leadEmail, $leadPhone);

        foreach ($superAdmins as $staff) {
            try {
                Mail::mailer('sendgrid')->to($staff->email)->send($mailable);
                Log::info('Signup notification sent to super admin', ['email' => $staff->email, 'client_id' => $clientId]);
            } catch (\Exception $e) {
                Log::error('Failed to send signup notification to super admin', [
                    'email' => $staff->email,
                    'client_id' => $clientId,
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }

    private function normalizePhoneForSignup(?string $phone, ?string $countryCode = null): string
    {
        if (empty($phone)) {
            return '';
        }
        $phone = trim($phone);
        $digits = preg_replace('/\D/', '', $phone);
        if ($countryCode && preg_match('/\+?(\d+)/', $countryCode, $m)) {
            $code = $m[1];
            $local = preg_replace('/^' . preg_quote($code, '/') . '/', '', $digits);
            if ($local !== $digits) {
                return '+' . $code . $local;
            }
            return '+' . $code . $digits;
        }
        if (str_starts_with($phone, '+')) {
            return '+' . $digits;
        }
        if (strlen($digits) === 9 && str_starts_with($digits, '4')) {
            return '+61' . $digits;
        }
        if (strlen($digits) === 10 && str_starts_with($digits, '0')) {
            return '+61' . substr($digits, 1);
        }
        if (strlen($digits) >= 10 && str_starts_with($digits, '61')) {
            return '+' . $digits;
        }
        return '+61' . $digits;
    }

    private function extractCountryCodeForSignup(?string $phone, ?string $countryCode = null): ?string
    {
        if ($countryCode && preg_match('/\+?(\d{1,4})/', trim($countryCode), $m)) {
            return '+' . $m[1];
        }
        if (empty($phone)) {
            return null;
        }
        $digits = preg_replace('/\D/', '', $phone);
        if (strlen($digits) >= 2 && substr($digits, 0, 2) === '61') {
            return '+61';
        }
        if (strlen($digits) === 9 && $digits[0] === '4') {
            return '+61';
        }
        return '+61';
    }
}
