<?php

/**
 * Visa Pricing Estimator Configuration
 *
 * Data aligned with Australian Department of Home Affairs Visa Pricing Estimator:
 * https://immi.homeaffairs.gov.au/visas/visa-pricing-estimator
 *
 * Prices are in AUD. Update annually (typically 1 July). Source:
 * https://immi.homeaffairs.gov.au/visas/getting-a-visa/fees-and-charges
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Default charges for additional applicants (2025-26 rates)
    |--------------------------------------------------------------------------
    */
    'additional_applicant_charge_18_plus' => 4685,
    'additional_applicant_charge_u18' => 2345,

    /*
    |--------------------------------------------------------------------------
    | Visa list synced from visa_pricing_clean.xlsx (All Visa Pricing sheet)
    |--------------------------------------------------------------------------
    | id: sequential value from sheet row order
    | label: Visa Subclass column
    | base_charge: Base Application Charge
    | additional_18_plus: Additional Applicant Charge 18 And Over
    | additional_u18: Additional Applicant Charge Under 18
    | non_internet_app_charge: Non-Internet Application Charge
    | subsequent_temp_app_charge: Subsequent Temporary Application Charge
    | page: page column
    */
    'visas' => [
        [
            'id' => '1',
            'label' => 'Adoption visa (subclass 102)',
            'base_charge' => 3235,
            'additional_18_plus' => 1615,
            'additional_u18' => 810,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '2',
            'label' => 'Aged Dependent Relative visa (subclass 114)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '3',
            'label' => 'Aged Dependent Relative visa (subclass 838)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '4',
            'label' => 'Aged Parent (subclass 804)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '5',
            'label' => 'Australian Declaratory visa (zz 998) Adult - Inside Australia',
            'base_charge' => 185,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '6',
            'label' => 'Australian Declaratory visa (zz 998) Adult - Outside Australia',
            'base_charge' => 240,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '7',
            'label' => 'Australian Declaratory visa (zz 998) Child - Inside Australia',
            'base_charge' => 120,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '8',
            'label' => 'Australian Declaratory visa (zz 998) Child - Outside Australia',
            'base_charge' => 185,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '9',
            'label' => 'Border (subclass 773)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '10',
            'label' => 'Bridging visa A (BVA) (subclass 010)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '11',
            'label' => 'Bridging visa B (BVB) (subclass 020)',
            'base_charge' => 190,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '12',
            'label' => 'Bridging visa C (BVC) (subclass 030)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '13',
            'label' => 'Bridging visa D - BVD (subclass 040)',
            'base_charge' => null,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '14',
            'label' => 'Bridging visa E - BVE (subclass 050 and 051)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '15',
            'label' => 'Bridging visa F - BVF - (subclass 060)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '16',
            'label' => 'Business Innovation and Investment (Permanent) visa (subclass 888) - Business Innovation stream',
            'base_charge' => 3500,
            'additional_18_plus' => 1755,
            'additional_u18' => 875,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '17',
            'label' => 'Business Innovation and Investment (Permanent) visa (subclass 888) - Entrepreneur stream',
            'base_charge' => 3500,
            'additional_18_plus' => 1755,
            'additional_u18' => 875,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '18',
            'label' => 'Business Innovation and Investment (Permanent) visa (subclass 888) - Investor stream',
            'base_charge' => 3500,
            'additional_18_plus' => 1755,
            'additional_u18' => 875,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '19',
            'label' => 'Business Innovation and Investment (Permanent) visa (subclass 888) - Premium Investor stream',
            'base_charge' => 3500,
            'additional_18_plus' => 1755,
            'additional_u18' => 875,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '20',
            'label' => 'Business Innovation and Investment (Permanent) visa (subclass 888) - Significant Investor stream',
            'base_charge' => 3500,
            'additional_18_plus' => 1755,
            'additional_u18' => 875,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '21',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Business Innovation Extension stream',
            'base_charge' => 1205,
            'additional_18_plus' => 605,
            'additional_u18' => 305,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '22',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Business Innovation stream',
            'base_charge' => 10000,
            'additional_18_plus' => 5000,
            'additional_u18' => 2500,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '23',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Entrepreneur stream',
            'base_charge' => 6765,
            'additional_18_plus' => 3385,
            'additional_u18' => 1690,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '24',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Investor stream',
            'base_charge' => 10000,
            'additional_18_plus' => 5000,
            'additional_u18' => 2500,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '25',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Premium Investor stream',
            'base_charge' => 9455,
            'additional_18_plus' => 4725,
            'additional_u18' => 2365,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '26',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Significant Investor Extension stream',
            'base_charge' => 1205,
            'additional_18_plus' => 605,
            'additional_u18' => 305,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '27',
            'label' => 'Business Innovation and Investment (Provisional) visa (subclass 188) - Significant Investor stream',
            'base_charge' => 14670,
            'additional_18_plus' => 7335,
            'additional_u18' => 3670,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '28',
            'label' => 'Business Owner visa (subclass 890)',
            'base_charge' => 2890,
            'additional_18_plus' => 1445,
            'additional_u18' => 720,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '29',
            'label' => 'Business Talent (subclass 132) - Significant Business History',
            'base_charge' => 7855,
            'additional_18_plus' => 3930,
            'additional_u18' => 1960,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '30',
            'label' => 'Carer visa (subclass 116)',
            'base_charge' => 2175,
            'additional_18_plus' => 1090,
            'additional_u18' => 545,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '31',
            'label' => 'Carer visa (subclass 836)',
            'base_charge' => 2175,
            'additional_18_plus' => 1090,
            'additional_u18' => 545,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '32',
            'label' => 'Child visa (subclass 101)',
            'base_charge' => 3235,
            'additional_18_plus' => 1615,
            'additional_u18' => 810,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '33',
            'label' => 'Child visa (subclass 802)',
            'base_charge' => 3235,
            'additional_18_plus' => 1615,
            'additional_u18' => 810,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '34',
            'label' => 'Child visa (subclass 802) - State Government supported',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '35',
            'label' => 'Confirmatory (Residence) visa (subclass 808)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '36',
            'label' => 'Confirmatory (Residence) visa (subclass 808) - Previous holder of subclass 773 visa',
            'base_charge' => 365,
            'additional_18_plus' => 185,
            'additional_u18' => 95,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '37',
            'label' => 'Contributory Aged Parent (Temporary) visa (subclass 884)',
            'base_charge' => 5040,
            'additional_18_plus' => 2515,
            'additional_u18' => 1260,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '38',
            'label' => 'Contributory Aged Parent (Temporary) visa (subclass 884) - Newborn and other applicants',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '39',
            'label' => 'Contributory Aged Parent visa (subclass 864) - any other applicants see note',
            'base_charge' => 5040,
            'additional_18_plus' => 2515,
            'additional_u18' => 1260,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '40',
            'label' => 'Contributory Aged Parent visa (subclass 864) - see note for eligibility',
            'base_charge' => 445,
            'additional_18_plus' => 225,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '41',
            'label' => 'Contributory Aged Parent visa (subclass 864) - see note for eligibility',
            'base_charge' => 5040,
            'additional_18_plus' => 2515,
            'additional_u18' => 1260,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '42',
            'label' => 'Contributory Aged Parent visa (subclass 864) - see note for eligibility',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '43',
            'label' => 'Contributory Parent (Temporary) visa (subclass 173)',
            'base_charge' => 3395,
            'additional_18_plus' => 1700,
            'additional_u18' => 855,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '44',
            'label' => 'Contributory Parent (Temporary) visa (subclass 173) - see note for eligibility',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '45',
            'label' => 'Contributory Parent visa (subclass 143) - Applicant meets conditions defined in Note 19b',
            'base_charge' => 445,
            'additional_18_plus' => 225,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '46',
            'label' => 'Contributory Parent visa (subclass 143) - Applicant meets conditions defined in Note 19c',
            'base_charge' => 3235,
            'additional_18_plus' => 1615,
            'additional_u18' => 810,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '47',
            'label' => 'Contributory Parent visa (subclass 143) - Applicant meets conditions defined in Note 19d',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '48',
            'label' => 'Contributory Parent visa (subclass 143) - Applicant meets conditions defined in Note 19d2',
            'base_charge' => 5040,
            'additional_18_plus' => 1700,
            'additional_u18' => 855,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '49',
            'label' => 'Dependent Child visa (subclass 445)',
            'base_charge' => 3235,
            'additional_18_plus' => 1615,
            'additional_u18' => 810,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '50',
            'label' => 'Diplomatic (Temporary) (subclass 995)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 1,
        ],
        [
            'id' => '51',
            'label' => 'Distinguished Talent visa (subclass 124)',
            'base_charge' => 4110,
            'additional_18_plus' => 2055,
            'additional_u18' => 1030,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '52',
            'label' => 'Electronic Travel Authority (subclass 601)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '53',
            'label' => 'Employer Nomination Scheme visa (subclass 186) - Direct Entry stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '54',
            'label' => 'Employer Nomination Scheme visa (subclass 186) - Labour agreement stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '55',
            'label' => 'Employer Nomination Scheme visa (subclass 186) - Temporary Residence Transition stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '56',
            'label' => 'eVisitor (subclass 651)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '57',
            'label' => 'Former Resident visa (subclass 151)',
            'base_charge' => 4805,
            'additional_18_plus' => 2400,
            'additional_u18' => 1200,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '58',
            'label' => 'Global Special Humanitarian visa (subclass 202)',
            'base_charge' => 570,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '59',
            'label' => 'Investor Retirement visa (subclass 405)',
            'base_charge' => 505,
            'additional_18_plus' => 255,
            'additional_u18' => 125,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '60',
            'label' => 'Investor visa (subclass 891)',
            'base_charge' => 2890,
            'additional_18_plus' => 1445,
            'additional_u18' => 720,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '61',
            'label' => 'Maritime Crew visa (subclass 988)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '62',
            'label' => 'Medical Treatment visa (subclass 602) - Inside Australia',
            'base_charge' => 380,
            'additional_18_plus' => 190,
            'additional_u18' => 95,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '63',
            'label' => 'Medical Treatment visa (subclass 602) - Outside Australia',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '64',
            'label' => 'National Innovation visa (subclass 858)',
            'base_charge' => 4985,
            'additional_18_plus' => 2495,
            'additional_u18' => 1250,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '65',
            'label' => 'New Zealand Citizen Family Relationship (Temporary) visa (subclass 461)',
            'base_charge' => 445,
            'additional_18_plus' => 225,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '66',
            'label' => 'Orphan Relative visa (subclass 117)',
            'base_charge' => 1980,
            'additional_18_plus' => 990,
            'additional_u18' => 500,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '67',
            'label' => 'Orphan Relative visa (subclass 837)',
            'base_charge' => 1980,
            'additional_18_plus' => 990,
            'additional_u18' => 500,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '68',
            'label' => 'Pacific Engagement visa (subclass 192) - Pacific Engagement stream',
            'base_charge' => 335,
            'additional_18_plus' => 80,
            'additional_u18' => 80,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '69',
            'label' => 'Pacific Engagement visa (subclass 192) - Treat stream (Tuvalu)',
            'base_charge' => 200,
            'additional_18_plus' => 50,
            'additional_u18' => 50,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '70',
            'label' => 'Parent visa (subclass 103)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '71',
            'label' => 'Partner (Provisional and Migrant) visa (subclass 309/100)',
            'base_charge' => 9365,
            'additional_18_plus' => 4685,
            'additional_u18' => 2345,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '72',
            'label' => 'Partner visa (subclass 820/801)',
            'base_charge' => 9365,
            'additional_18_plus' => 4685,
            'additional_u18' => 2345,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '73',
            'label' => 'Partner visa (subclass 820/801) - Application by Prospective Marriage visa holder',
            'base_charge' => 1560,
            'additional_18_plus' => 785,
            'additional_u18' => 390,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '74',
            'label' => 'Partner visa (subclass 820/801) - Ceased Prospective Marriage visa',
            'base_charge' => 1980,
            'additional_18_plus' => 990,
            'additional_u18' => 500,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '75',
            'label' => 'Partner visa (subclass 820/801) - Transitional visa holder',
            'base_charge' => 560,
            'additional_18_plus' => 280,
            'additional_u18' => 145,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '76',
            'label' => 'Permanent Residence (Skilled Regional) visa (subclass 191) - Hong Kong stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2450,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '77',
            'label' => 'Permanent Residence (Skilled Regional) visa (subclass 191) Regional Provisional stream',
            'base_charge' => 505,
            'additional_18_plus' => 250,
            'additional_u18' => 130,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '78',
            'label' => 'Prospective Marriage visa (subclass 300)',
            'base_charge' => 9365,
            'additional_18_plus' => 4685,
            'additional_u18' => 2345,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '79',
            'label' => 'Protection visa (subclass 866) lodged in Australia',
            'base_charge' => 50,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '80',
            'label' => 'Provisional Resident Return visa (subclass 159)',
            'base_charge' => 245,
            'additional_18_plus' => 125,
            'additional_u18' => 60,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '81',
            'label' => 'Refugee category visas (Subclass 200, 201, 203 and 204)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '82',
            'label' => 'Regional Sponsored Migration Scheme visa (subclass 187) - Temporary Residence Transition stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '83',
            'label' => 'Remaining Relative visa (subclass 115)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '84',
            'label' => 'Remaining Relative visa (subclass 835)',
            'base_charge' => 5280,
            'additional_18_plus' => 2640,
            'additional_u18' => 1325,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '85',
            'label' => 'Resident Return visa (subclass 155/157)',
            'base_charge' => 490,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '86',
            'label' => 'Resolution of Status (subclass 851)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '87',
            'label' => 'Retirement visa (subclass 410)',
            'base_charge' => 500,
            'additional_18_plus' => 250,
            'additional_u18' => 125,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '88',
            'label' => 'Safe Haven Enterprise visa (subclass 790) - lodged in Australia by an applicant who is in immigration detention and not immigration cleared',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '89',
            'label' => 'Safe Haven Enterprise visa (subclass 790) lodged in Australia',
            'base_charge' => 50,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '90',
            'label' => 'Skilled - Recognised Graduate visa (subclass 476)',
            'base_charge' => 465,
            'additional_18_plus' => 230,
            'additional_u18' => 115,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '91',
            'label' => 'Skilled Employer Sponsored Regional (Provisional) visa (subclass 494) - Employer Sponsored stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '92',
            'label' => 'Skilled Employer Sponsored Regional (Provisional) visa (subclass 494) - Labour Agreement stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '93',
            'label' => 'Skilled Employer Sponsored Regional (Provisional) visa (subclass 494) - Subsequent entrant',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '94',
            'label' => 'Skilled Independent visa (subclass 189) - Hong Kong stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '95',
            'label' => 'Skilled Independent visa (subclass 189) - Points tested stream',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '96',
            'label' => 'Skilled Nominated visa (subclass 190)',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '97',
            'label' => 'Skilled Regional (Provisional) visa (subclass 489) - Extended stay pathway',
            'base_charge' => 435,
            'additional_18_plus' => 220,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '98',
            'label' => 'Skilled Regional (Provisional) visa (subclass 489) - Subsequent entry pathway',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '99',
            'label' => 'Skilled Regional visa (subclass 887)',
            'base_charge' => 505,
            'additional_18_plus' => 250,
            'additional_u18' => 130,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '100',
            'label' => 'Skilled Work Regional (Provisional) visa (subclass 491)',
            'base_charge' => 4910,
            'additional_18_plus' => 2455,
            'additional_u18' => 1230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 2,
        ],
        [
            'id' => '101',
            'label' => 'Skills in Demand Visa (subclass 482) - Core Skills stream',
            'base_charge' => 3210,
            'additional_18_plus' => 3210,
            'additional_u18' => 805,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '102',
            'label' => 'Skills in Demand visa (subclass 482) - Labour agreement stream',
            'base_charge' => 3210,
            'additional_18_plus' => 3210,
            'additional_u18' => 805,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '103',
            'label' => 'Skills in Demand visa (subclass 482) - Specialist Skills stream',
            'base_charge' => 3210,
            'additional_18_plus' => 3210,
            'additional_u18' => 805,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '104',
            'label' => 'Special Category visa (subclass 444)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '105',
            'label' => 'Sponsored Parent (temporary) visa (subclass 870)',
            'base_charge' => 1215,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '106',
            'label' => 'State or Territory Sponsored Business Owner visa (subclass 892)',
            'base_charge' => 2890,
            'additional_18_plus' => 1445,
            'additional_u18' => 720,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '107',
            'label' => 'State or Territory Sponsored Investor visa (subclass 893)',
            'base_charge' => 2890,
            'additional_18_plus' => 1445,
            'additional_u18' => 720,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '108',
            'label' => 'Student Guardian visa (subclass 590)',
            'base_charge' => 2000,
            'additional_18_plus' => 0,
            'additional_u18' => 400,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '109',
            'label' => 'Student Guardian visa (subclass 590) - eligible Pacific Island and Timor-Leste Student and Student Guardian visa applicants',
            'base_charge' => 730,
            'additional_18_plus' => null,
            'additional_u18' => 180,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '110',
            'label' => 'Student visa (subclass 500) - All other students',
            'base_charge' => 2000,
            'additional_18_plus' => 1225,
            'additional_u18' => 400,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '111',
            'label' => 'Student visa (subclass 500) - All other students - eligible Pacific Island and Timor-Leste Student and Student Guardian visa applicants',
            'base_charge' => 730,
            'additional_18_plus' => 545,
            'additional_u18' => 180,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '112',
            'label' => 'Student visa (subclass 500) - Foreign Affairs or Defence sector',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '113',
            'label' => 'Student visa (subclass 500) - Postgraduate research sector',
            'base_charge' => 2000,
            'additional_18_plus' => 0,
            'additional_u18' => 0,
            'non_internet_app_charge' => 0,
            'subsequent_temp_app_charge' => 0,
            'page' => 3,
        ],
        [
            'id' => '114',
            'label' => 'Student visa (subclass 500) - Postgraduate research sector - eligible Pacific Island and Timor-Leste Student and Student Guardian visa applicants',
            'base_charge' => 730,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '115',
            'label' => 'Student visa (subclass 500) - Secondary exchange (Schools sector)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '116',
            'label' => 'Temporary Activity visa (subclass 408) - Australian Government Endorsed Events stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '117',
            'label' => 'Temporary Activity visa (subclass 408) - Domestic Work for Executives stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '118',
            'label' => 'Temporary Activity visa (subclass 408) - Entertainment Activities stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '119',
            'label' => 'Temporary Activity visa (subclass 408) - Other Social and Cultural Activity (Invited Participant) stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '120',
            'label' => 'Temporary Activity visa (subclass 408) - Religious Work stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '121',
            'label' => 'Temporary Activity visa (subclass 408) - Research Activities stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '122',
            'label' => 'Temporary Activity visa (subclass 408) - Special Program stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '123',
            'label' => 'Temporary Activity visa (subclass 408) - Sporting Activities stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '124',
            'label' => 'Temporary Activity visa (subclass 408) - Staff Exchange Arrangements stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '125',
            'label' => 'Temporary Activity visa (subclass 408) - Superyacht Crew stream',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '126',
            'label' => 'Temporary Graduate visa (subclass 485) - Post-Higher Education Work stream',
            'base_charge' => 4600,
            'additional_18_plus' => 2300,
            'additional_u18' => 1160,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '127',
            'label' => 'Temporary Graduate visa (subclass 485) - Post-Higher Education Work stream – eligible Pacific Island and Timor Leste visa applicants',
            'base_charge' => 2300,
            'additional_18_plus' => 1150,
            'additional_u18' => 580,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '128',
            'label' => 'Temporary Graduate visa (subclass 485) - Post-Vocational Education Work stream',
            'base_charge' => 4600,
            'additional_18_plus' => 2300,
            'additional_u18' => 1160,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '129',
            'label' => 'Temporary Graduate visa (subclass 485) - Post-Vocational Education Work stream – eligible Pacific Island and Timor Leste visa applicants',
            'base_charge' => 2300,
            'additional_18_plus' => 1150,
            'additional_u18' => 580,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '130',
            'label' => 'Temporary Graduate visa (subclass 485) - Second Post-Higher Education Work stream',
            'base_charge' => 1810,
            'additional_18_plus' => 910,
            'additional_u18' => 460,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '131',
            'label' => 'Temporary Graduate visa (subclass 485) - Second Post-Higher Education Work stream – eligible Pacific Island and Timor Leste visa applicants',
            'base_charge' => 905,
            'additional_18_plus' => 455,
            'additional_u18' => 230,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '132',
            'label' => 'Temporary Protection visa (subclass 785) - lodged in Australia by an applicant who is in immigration detention and not immigration cleared',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '133',
            'label' => 'Temporary Protection visa (subclass 785) lodged in Australia',
            'base_charge' => 50,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '134',
            'label' => 'Temporary Work (International Relations) visa (subclass 403) - Domestic Worker (Diplomatic or Consular) stream',
            'base_charge' => 375,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '135',
            'label' => 'Temporary Work (International Relations) visa (subclass 403) - Foreign Government stream',
            'base_charge' => 375,
            'additional_18_plus' => 375,
            'additional_u18' => 95,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '136',
            'label' => 'Temporary Work (International Relations) visa (subclass 403) - Government Agreement stream',
            'base_charge' => 375,
            'additional_18_plus' => 375,
            'additional_u18' => 95,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '137',
            'label' => 'Temporary work (International relations) visa (subclass 403) - Mobility Arrangement for Talented Early-professionals Scheme (MATES)',
            'base_charge' => 375,
            'additional_18_plus' => 375,
            'additional_u18' => 95,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '138',
            'label' => 'Temporary Work (International Relations) visa (subclass 403) - Pacific Australia Labour Mobility stream',
            'base_charge' => 355,
            'additional_18_plus' => 345,
            'additional_u18' => 80,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '139',
            'label' => 'Temporary Work (International Relations) visa (subclass 403) - Privileges and Immunities stream',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '140',
            'label' => 'Temporary Work (Short Stay Specialist) visa (subclass 400)',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '141',
            'label' => 'Training visa (subclass 407)',
            'base_charge' => 430,
            'additional_18_plus' => 430,
            'additional_u18' => 110,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '142',
            'label' => 'Transit visa (subclass 771)',
            'base_charge' => 0,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '143',
            'label' => 'Visitor visa (subclass 600) - Approved Destination Status stream',
            'base_charge' => 200,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '144',
            'label' => 'Visitor visa (subclass 600) - Business Visitor stream',
            'base_charge' => 200,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '145',
            'label' => 'Visitor visa (subclass 600) - Frequent traveller stream',
            'base_charge' => 1480,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '146',
            'label' => 'Visitor visa (subclass 600) - Sponsored Family stream',
            'base_charge' => 200,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '147',
            'label' => 'Visitor visa (subclass 600) Tourist stream - In Australia',
            'base_charge' => 500,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => 700,
            'page' => 3,
        ],
        [
            'id' => '148',
            'label' => 'Visitor visa (subclass 600) Tourist stream - outside Australia',
            'base_charge' => 200,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '149',
            'label' => 'Work and Holiday visa (subclass 462) - First',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => null,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '150',
            'label' => 'Work and Holiday visa (subclass 462) - Second',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 3,
        ],
        [
            'id' => '151',
            'label' => 'Work and Holiday visa (subclass 462) - Third',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 4,
        ],
        [
            'id' => '152',
            'label' => 'Working Holiday visa (subclass 417) - First',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 4,
        ],
        [
            'id' => '153',
            'label' => 'Working Holiday visa (subclass 417) - Second',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 4,
        ],
        [
            'id' => '154',
            'label' => 'Working Holiday visa (subclass 417) - Third',
            'base_charge' => 670,
            'additional_18_plus' => null,
            'additional_u18' => null,
            'non_internet_app_charge' => 80,
            'subsequent_temp_app_charge' => null,
            'page' => 4,
        ],
    ],

];
